// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const configuredDatabaseUrl = process.env["DATABASE_URL"]?.trim();
const databaseUrl =
  !configuredDatabaseUrl || configuredDatabaseUrl === "file:./dev.db"
    ? "file:./prisma/dev.db"
    : configuredDatabaseUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
